// <auto-generated />
namespace ProjetoOng_EF_DF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Metodos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Metodos));
        
        string IMigrationMetadata.Id
        {
            get { return "202210152111087_Metodos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
